name:        bzlib-conduit
version:     0.3.0.4
synopsis:    Streaming compression/decompression via conduits.
description: Please see the README and docs at <https://www.stackage.org/package/bzlib-conduit>
category:    Codec
author:      Hideyuki Tanaka
maintainer:  Michael Snoyman
copyright:   (c) 2012, Hideyuki Tanaka
license:     BSD3
github:      snoyberg/bzlib-conduit

extra-source-files:
- README.md
- ChangeLog.md

dependencies:
- base >=4.9 && <10
- bytestring >= 0.9
- mtl >= 2.0
- conduit >= 1.3
- resourcet >= 1.2
- data-default-class
- bindings-DSL

flags:
  system-bzip2:
    description: Use system bzip2 instead of bundled sources
    manual: True
    default: True

library:
  source-dirs: src
  when:
  - condition: "!(os(windows)) && flag(system-bzip2)"
    then:
      extra-libraries: bz2
    else:
      dependencies: bzip2-clib

tests:
  test:
    main: test.hs
    source-dirs: test
    dependencies:
    - hspec >=1.3
    - random
    - bzlib-conduit

benchmarks:
  bench:
    main: bench.hs
    source-dirs: bench
    dependencies:
    - bzlib-conduit

data-files:
- test/*.bz2
- test/*.ref
